# Vendored from nliaudat/esphome_ai_component (MIT). See ATTRIBUTION.md.
wifi:
  id: ${id_prefix}_wifi_component
  networks:
    - ssid: !secret wifi_ssid_1
      password: !secret wifi_password_1
      priority: 1
    - ssid: !secret wifi_ssid_2
      password: !secret wifi_password_2
      priority: 2

  # Fallback captive-portal hotspot if Wi-Fi fails.
  ap:
    ssid: "${name} Flbck"
    password: !secret fallback_hotspot_password

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
    entity_category: "diagnostic"
    id: ${id_prefix}_wifi_signal_db
